#nginx-service.yaml

apiVersion: v1
kind: Service
metadata:
  name: nginx-svc3
spec:
  type: NodePort
  ports:
    - port: 9003  # service即ClusterPort
      targetPort: 80 # PodPort 
      nodePort: 30003 # NodePort,所有的Node都打开此端口
  selector:
    app: nginx-web3
