# nginx-pod2.yaml, 完成端口映射

apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-singlel2
spec:
  containers:
  - name: nginx-single
    image: "nginx"
    ports: 
    - name: http
      containerPort: 80
      hostPort: 8000 
      protocol: TCP
# 80 映射到node的8000,此方式容易现冲突，且无法确认在哪一个POD上，极不建议